kind: pipeline
type: kubernetes
name: default

concurrency:
  limit: 1

environment:
  ARGOCD_SERVER: argo.arthur-joly.fr

steps:
  - name: Build and plublish docker image
    image: plugins/buildah-docker:1.2.0-linux-amd64
    privileged: true
    settings:
      tags: latest
      registry: ghcr.io
      repo: ghcr.io/mangiang/mergedsecretsoperator
      username:
        from_secret: GITHUB_REGISTRY_USERNAME
      password:
        from_secret: GITHUB_REGISTRY_TOKEN
  - name: Resync CRDS
    image: node:latest
    environment:
      ARGOCD_USERNAME:
        from_secret: ARGOCD_USERNAME
      ARGOCD_PASSWORD:
        from_secret: ARGOCD_PASSWORD
    commands:
      - wget -O argocd https://$ARGOCD_SERVER/download/argocd-linux-amd64
      - chmod +x argocd
      - ./argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
      - ./argocd app sync merged-secrets-operator-crds
      - ./argocd app sync merged-secrets-operator-rbac
      - ./argocd app sync merged-secrets-operator-operator
