kind: pipeline
type: kubernetes
name: default

concurrency:
  limit: 1

environment:
  ARGOCD_SERVER: argo.arthur-joly.fr

steps:
  - name: Build and plublish docker image
    image: plugins/buildah-docker:1.2.0-linux-amd64
    privileged: true
    settings:
      tags: latest
      registry: ghcr.io
      repo: ghcr.io/mangiang/mergedsecretsoperator
      username:
        from_secret: GITHUB_REGISTRY_USERNAME
      password:
        from_secret: GITHUB_REGISTRY_TOKEN
  - name: Resync CRDS
    image: node:latest
    environment:
      ARGOCD_USERNAME:
        from_secret: ARGOCD_USERNAME
      ARGOCD_PASSWORD:
        from_secret: ARGOCD_PASSWORD
    commands:
      - wget -O argo/argocd https://$ARGOCD_SERVER/download/argocd-linux-amd64
      - chmod +x argo/argocd
      - argo/argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
      - argo/argocd app sync merged-secrets-operator-crds
    volumes:
      - name: crds
        path: /argo
    depends_on:
      - Build and plublish docker image
  - name: Resync RBAC
    image: node:latest
    environment:
      ARGOCD_USERNAME:
        from_secret: ARGOCD_USERNAME
      ARGOCD_PASSWORD:
        from_secret: ARGOCD_PASSWORD
    commands:
      - wget -O argo/argocd https://$ARGOCD_SERVER/download/argocd-linux-amd64
      - chmod +x argo/argocd
      - argo/argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
      - argo/argocd app sync merged-secrets-operator-rbac
    volumes:
      - name: crds
        path: /argo
    depends_on:
      - Build and plublish docker image
  - name: Resync Operator
    image: node:latest
    environment:
      ARGOCD_USERNAME:
        from_secret: ARGOCD_USERNAME
      ARGOCD_PASSWORD:
        from_secret: ARGOCD_PASSWORD
    commands:
      - wget -O argocd https://$ARGOCD_SERVER/download/argocd-linux-amd64
      - chmod +x argocd
      - argo/argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD
      - argo/argocd app sync merged-secrets-operator-operator
    volumes:
      - name: operator
        path: /argo
    depends_on:
      - Build and plublish docker image

volumes:
  - name: crds
    temp:
      medium: memory
  - name: rbac
    temp:
      medium: memory
  - name: operator
    temp:
      medium: memory
