apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mergedsecrets.arthur-joly.fr
spec:
  scope: Namespaced
  group: arthur-joly.fr
  names:
    kind: MergedSecret
    plural: mergedsecrets
    singular: mergedsecret
    shortNames:
      - ms
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
