apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kopf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopf
subjects:
  - kind: ServiceAccount
    name: merged-secrets
    namespace: mergedsecrets
